baseURL = 'https://www.malcolmmckinney.com/'
languageCode = 'en-us'
title = 'Malcolm\'s portfolio'
theme = 'introduction'
DefaultContentLanguage = 'en'

[params]
    themeStyle = 'auto'
    customCSS = ['/css/form-reset.css']

    [[params.social]]
        icon = 'linkedin'
        icon_pack = 'fab'
        url = '//linkedin.com/in/malcolmmckinney/'

    [[params.social]]
        name = 'instagram'
        icon_pack = 'fa-instagram'
        url = '//instagram.com/m.shinjuku'

    [[params.social]]
        icon = 'github'
        icon_pack = 'fab'
        link = '//github.com/malcolm-mckinney'

    [[params.social]]
        icon = 'envelope'
        icon_pack = 'fa'
        url = 'mailto:contact@malcolmmckinney.com'


